export const COLOR_PINK_50 = '#fdecf2';
export const COLOR_PINK_100 = '#f9c4d6';
export const COLOR_PINK_200 = '#f6a7c2';
export const COLOR_PINK_300 = '#f27fa6';
export const COLOR_PINK_400 = '#f06695';
export const COLOR_PINK_400_ALPHA008 = '#f0669514';
export const COLOR_PINK_400_ALPHA016 = '#f0669529';
export const COLOR_PINK_500 = '#ec407a';
export const COLOR_PINK_500_ALPHA004 = '#ec407aa';
export const COLOR_PINK_500_ALPHA008 = '#ec407a14';
export const COLOR_PINK_600 = '#d73a6f';
export const COLOR_PINK_700 = '#a82d57';
export const COLOR_PINK_800 = '#822343';
export const COLOR_PINK_900 = '#631b33';
export const COLOR_GREEN_50 = '#e6faf0';
export const COLOR_GREEN_100 = '#b0efd1';
export const COLOR_GREEN_200 = '#8ae7bb';
export const COLOR_GREEN_300 = '#54dc9d';
export const COLOR_GREEN_400 = '#33d589';
export const COLOR_GREEN_500 = '#00cb6c';
export const COLOR_GREEN_600 = '#00b962';
export const COLOR_GREEN_700 = '#00904d';
export const COLOR_GREEN_800 = '#00703b';
export const COLOR_GREEN_900 = '#00552d';
export const COLOR_BLUE_GREEN_50 = '#e8fcf8';
export const COLOR_BLUE_GREEN_100 = '#bef3e9';
export const COLOR_BLUE_GREEN_200 = '#99e5d6';
export const COLOR_BLUE_GREEN_300 = '#7ad3c1';
export const COLOR_BLUE_GREEN_400 = '#35c4b0';
export const COLOR_BLUE_GREEN_500 = '#00af9a';
export const COLOR_BLUE_GREEN_600 = '#009b85';
export const COLOR_BLUE_GREEN_700 = '#008371';
export const COLOR_BLUE_GREEN_800 = '#006b5b';
export const COLOR_BLUE_GREEN_900 = '#004437';
export const COLOR_LIGHT_GRAY_50 = '#fdfdff';
export const COLOR_LIGHT_GRAY_100 = '#fbfbfd';
export const COLOR_LIGHT_GRAY_200 = '#f9f9fb';
export const COLOR_LIGHT_GRAY_300 = '#f6f6f8';
export const COLOR_LIGHT_GRAY_400 = '#f4f4f6';
export const COLOR_LIGHT_GRAY_500 = '#f1f1f4';
export const COLOR_LIGHT_GRAY_600 = '#dbdbde';
export const COLOR_LIGHT_GRAY_700 = '#ababae';
export const COLOR_LIGHT_GRAY_800 = '#858587';
export const COLOR_LIGHT_GRAY_900 = '#656567';
export const COLOR_GRAY_50 = '#f0f2f4';
export const COLOR_GRAY_50_ALPHA008 = '#f0f2f414';
export const COLOR_GRAY_50_ALPHA016 = '#f0f2f429';
export const COLOR_GRAY_100 = '#d1d6dc';
export const COLOR_GRAY_200 = '#bbc2cb';
export const COLOR_GRAY_300 = '#9da7b4';
export const COLOR_GRAY_400 = '#8995a5';
export const COLOR_GRAY_500 = '#6c7b8f';
export const COLOR_GRAY_600 = '#627082';
export const COLOR_GRAY_700 = '#4d5b6e';
export const COLOR_GRAY_800 = '#2c3c52';
export const COLOR_GRAY_850 = '#243245';
export const COLOR_GRAY_900 = '#1f2d40';
export const COLOR_GRAY_900_ALPHA004 = '#1f2d40a';
export const COLOR_GRAY_900_ALPHA008 = '#1f2d4014';
export const COLOR_GRAY_950 = '#182230';
export const COLOR_NEUTRAL_WHITE = '#ffffff';
export const COLOR_NEUTRAL_BLACK = '#000000';
export const COLOR_YELLOW_500 = '#ffce00';
export const COLOR_YELLOW_800 = '#cca500';
export const COLOR_RED_400 = '#ff002e';
export const COLOR_RED_500 = '#d32f2f';
export const COLOR_RED_600 = '#c62828';
export const ICON_PRIMARY = {
  light: COLOR_GRAY_600,
  dark: COLOR_GRAY_50,
};
export const ICON_LOGO_SYMBOL = {
  light: COLOR_PINK_500,
  dark: COLOR_GRAY_50,
};
export const ICON_LOGO_TEXT = {
  light: COLOR_GRAY_800,
  dark: COLOR_GRAY_50,
};
export const ICON_PRIMARY_HOVER = {
  light: COLOR_GRAY_800,
  dark: COLOR_NEUTRAL_WHITE,
};
export const ICON_PRIMARY_ACTIVE = {
  light: COLOR_PINK_600,
  dark: COLOR_PINK_400,
};
export const ICON_SECONDARY = {
  light: COLOR_GRAY_400,
  dark: COLOR_GRAY_200,
};
export const ICON_SECONDARY_HOVER = {
  light: COLOR_GRAY_600,
  dark: COLOR_GRAY_50,
};
export const ICON_BACKGROUND_SECONDARY_HOVER = {
  light: COLOR_GRAY_900_ALPHA004,
  dark: COLOR_GRAY_50_ALPHA008,
};
export const ICON_SECONDARY_ACTIVE = {
  light: COLOR_PINK_600,
  dark: COLOR_PINK_400,
};
export const ICON_BACKGROUND_SECONDARY_ACTIVE = {
  light: COLOR_PINK_500_ALPHA004,
  dark: COLOR_PINK_400_ALPHA008,
};
export const TEXT_PRIMARY = {
  light: COLOR_GRAY_800,
  dark: COLOR_GRAY_50,
};
export const TEXT_SECONDARY = {
  light: COLOR_GRAY_300,
  dark: COLOR_GRAY_200,
};
export const SURFACE_BACKGROUND_TOP_BAR = {
  light: COLOR_NEUTRAL_WHITE,
  dark: COLOR_GRAY_950,
};
export const SURFACE_BACKGROUND_PRIMARY = {
  light: COLOR_LIGHT_GRAY_50,
  dark: COLOR_GRAY_900,
};
export const SURFACE_BACKGROUND_PRIMARY_HOVER = {
  light: COLOR_LIGHT_GRAY_100,
  dark: COLOR_GRAY_850,
};
export const SURFACE_BACKGROUND_PRIMARY_ACTIVE = {
  light: COLOR_LIGHT_GRAY_200,
  dark: COLOR_GRAY_800,
};
export const SURFACE_BACKGROUND_DRAG_DROP = {
  light: COLOR_NEUTRAL_WHITE,
  dark: COLOR_GRAY_950,
};
export const SURFACE_BACKGROUND_SECONDARY = {
  light: COLOR_NEUTRAL_WHITE,
  dark: COLOR_GRAY_950,
};
export const BORDER_LINE_PRIMARY = {
  light: COLOR_GRAY_50,
  dark: COLOR_GRAY_700,
};
export const BORDER_PRIMARY = {
  light: COLOR_GRAY_100,
  dark: COLOR_GRAY_700,
};
export const BORDER_PRIMARY_HOVER = {
  light: COLOR_GRAY_200,
  dark: COLOR_GRAY_600,
};
export const BORDER_SECONDARY = {
  light: COLOR_GRAY_50,
  dark: COLOR_GRAY_700,
};
export const BORDER_SECONDARY_DASHED = {
  light: COLOR_GRAY_100,
  dark: COLOR_GRAY_700,
};
export const STATE_UNTRANSLATED = {
  light: COLOR_GRAY_200,
  dark: COLOR_GRAY_400,
};
export const STATE_TRANSLATED = {
  light: COLOR_YELLOW_500,
  dark: COLOR_YELLOW_800,
};
export const STATE_REVIEWED = {
  light: COLOR_GREEN_600,
  dark: COLOR_GREEN_700,
};
export const COMPONENTS_LINK_TEXT_PRIMARY = {
  light: COLOR_PINK_500,
  dark: COLOR_PINK_400,
};
export const COMPONENTS_BUTTON_BACKGROUND_PRIMARY = {
  light: COLOR_PINK_500,
  dark: COLOR_PINK_400,
};
export const COMPONENTS_BUTTON_BACKGROUND_PRIMARY_HOVER = {
  light: COLOR_PINK_600,
  dark: COLOR_PINK_500,
};
export const COMPONENTS_BUTTON_TEXT_PRIMARY = {
  light: COLOR_NEUTRAL_WHITE,
  dark: COLOR_GRAY_950,
};
export const COMPONENTS_BUTTON_BORDER_PRIMARY_OUTLINE = {
  light: COLOR_PINK_500,
  dark: COLOR_PINK_400,
};
export const COMPONENTS_BUTTON_BORDER_PRIMARY_OUTLINE_HOVER = {
  light: COLOR_PINK_600,
  dark: COLOR_PINK_500,
};
export const COMPONENTS_BUTTON_TEXT_PRIMARY_OUTLINE = {
  light: COLOR_PINK_500,
  dark: COLOR_PINK_400,
};
export const COMPONENTS_BUTTON_TEXT_PRIMARY_OUTLINE_HOVER = {
  light: COLOR_PINK_600,
  dark: COLOR_PINK_500,
};
export const COMPONENTS_BUTTON_BACKGROUND_SECONDARY_HOVER = {
  light: COLOR_LIGHT_GRAY_200,
  dark: COLOR_GRAY_800,
};
export const COMPONENTS_BUTTON_TEXT_SECONDARY = {
  light: COLOR_GRAY_700,
  dark: COLOR_GRAY_100,
};
export const COMPONENTS_BUTTON_TEXT_SECONDARY_HOVER = {
  light: COLOR_GRAY_900,
  dark: COLOR_GRAY_50,
};
export const COMPONENTS_BUTTON_TEXT_SECONDARY_OUTLINE = {
  light: COLOR_GRAY_700,
  dark: COLOR_GRAY_100,
};
export const COMPONENTS_BUTTON_BORDER_SECONDARY_OUTLINE = {
  light: COLOR_GRAY_200,
  dark: COLOR_GRAY_600,
};
export const COMPONENTS_BUTTON_BACKGROUND_TERTIARY = {
  light: COLOR_LIGHT_GRAY_300,
  dark: COLOR_GRAY_700,
};
export const COMPONENTS_BUTTON_BACKGROUND_TERTIARY_HOVER = {
  light: COLOR_LIGHT_GRAY_400,
  dark: COLOR_GRAY_600,
};
export const COMPONENTS_INPUT_BORDER_PRIMARY = {
  light: COLOR_GRAY_200,
  dark: COLOR_GRAY_600,
};
export const COMPONENTS_MENU_BACKGROUND = {
  light: COLOR_NEUTRAL_WHITE,
  dark: COLOR_GRAY_800,
};
export const COMPONENTS_MENU_ITEM_TEXT = TEXT_PRIMARY;
export const COMPONENTS_MENU_ITEM_TEXT_ACTION = {
  light: COLOR_PINK_600,
  dark: COLOR_PINK_400,
};
export const COMPONENTS_MENU_ITEM_BACKGROUND_HOVER = {
  light: COLOR_GRAY_900_ALPHA004,
  dark: COLOR_GRAY_50_ALPHA008,
};
export const COMPONENTS_MENU_ITEM_BACKGROUND_ACTIVE = {
  light: COLOR_PINK_500_ALPHA008,
  dark: COLOR_PINK_400_ALPHA016,
};
export const COMPONENTS_INPUT_BACKGROUND_PRIMARY = {
  light: COLOR_NEUTRAL_WHITE,
  dark: COLOR_GRAY_900,
};

export const ALL_TOKENS = {
  COLOR_PINK_50,
  COLOR_PINK_100,
  COLOR_PINK_200,
  COLOR_PINK_300,
  COLOR_PINK_400,
  COLOR_PINK_400_ALPHA008,
  COLOR_PINK_400_ALPHA016,
  COLOR_PINK_500,
  COLOR_PINK_500_ALPHA004,
  COLOR_PINK_500_ALPHA008,
  COLOR_PINK_600,
  COLOR_PINK_700,
  COLOR_PINK_800,
  COLOR_PINK_900,
  COLOR_GREEN_50,
  COLOR_GREEN_100,
  COLOR_GREEN_200,
  COLOR_GREEN_300,
  COLOR_GREEN_400,
  COLOR_GREEN_500,
  COLOR_GREEN_600,
  COLOR_GREEN_700,
  COLOR_GREEN_800,
  COLOR_GREEN_900,
  COLOR_BLUE_GREEN_50,
  COLOR_BLUE_GREEN_100,
  COLOR_BLUE_GREEN_200,
  COLOR_BLUE_GREEN_300,
  COLOR_BLUE_GREEN_400,
  COLOR_BLUE_GREEN_500,
  COLOR_BLUE_GREEN_600,
  COLOR_BLUE_GREEN_700,
  COLOR_BLUE_GREEN_800,
  COLOR_BLUE_GREEN_900,
  COLOR_LIGHT_GRAY_50,
  COLOR_LIGHT_GRAY_100,
  COLOR_LIGHT_GRAY_200,
  COLOR_LIGHT_GRAY_300,
  COLOR_LIGHT_GRAY_400,
  COLOR_LIGHT_GRAY_500,
  COLOR_LIGHT_GRAY_600,
  COLOR_LIGHT_GRAY_700,
  COLOR_LIGHT_GRAY_800,
  COLOR_LIGHT_GRAY_900,
  COLOR_GRAY_50,
  COLOR_GRAY_50_ALPHA008,
  COLOR_GRAY_50_ALPHA016,
  COLOR_GRAY_100,
  COLOR_GRAY_200,
  COLOR_GRAY_300,
  COLOR_GRAY_400,
  COLOR_GRAY_500,
  COLOR_GRAY_600,
  COLOR_GRAY_700,
  COLOR_GRAY_800,
  COLOR_GRAY_850,
  COLOR_GRAY_900,
  COLOR_GRAY_900_ALPHA004,
  COLOR_GRAY_900_ALPHA008,
  COLOR_GRAY_950,
  COLOR_NEUTRAL_WHITE,
  COLOR_NEUTRAL_BLACK,
  COLOR_YELLOW_500,
  COLOR_YELLOW_800,
  COLOR_RED_400,
  COLOR_RED_500,
  COLOR_RED_600,
  ICON_PRIMARY,
  ICON_LOGO_SYMBOL,
  ICON_LOGO_TEXT,
  ICON_PRIMARY_HOVER,
  ICON_PRIMARY_ACTIVE,
  ICON_SECONDARY,
  ICON_SECONDARY_HOVER,
  ICON_BACKGROUND_SECONDARY_HOVER,
  ICON_SECONDARY_ACTIVE,
  ICON_BACKGROUND_SECONDARY_ACTIVE,
  TEXT_PRIMARY,
  TEXT_SECONDARY,
  SURFACE_BACKGROUND_TOP_BAR,
  SURFACE_BACKGROUND_PRIMARY,
  SURFACE_BACKGROUND_PRIMARY_HOVER,
  SURFACE_BACKGROUND_PRIMARY_ACTIVE,
  SURFACE_BACKGROUND_DRAG_DROP,
  SURFACE_BACKGROUND_SECONDARY,
  BORDER_LINE_PRIMARY,
  BORDER_PRIMARY,
  BORDER_PRIMARY_HOVER,
  BORDER_SECONDARY,
  BORDER_SECONDARY_DASHED,
  STATE_UNTRANSLATED,
  STATE_TRANSLATED,
  STATE_REVIEWED,
  COMPONENTS_LINK_TEXT_PRIMARY,
  COMPONENTS_BUTTON_BACKGROUND_PRIMARY,
  COMPONENTS_BUTTON_BACKGROUND_PRIMARY_HOVER,
  COMPONENTS_BUTTON_TEXT_PRIMARY,
  COMPONENTS_BUTTON_BORDER_PRIMARY_OUTLINE,
  COMPONENTS_BUTTON_BORDER_PRIMARY_OUTLINE_HOVER,
  COMPONENTS_BUTTON_TEXT_PRIMARY_OUTLINE,
  COMPONENTS_BUTTON_TEXT_PRIMARY_OUTLINE_HOVER,
  COMPONENTS_BUTTON_BACKGROUND_SECONDARY_HOVER,
  COMPONENTS_BUTTON_TEXT_SECONDARY,
  COMPONENTS_BUTTON_TEXT_SECONDARY_HOVER,
  COMPONENTS_BUTTON_TEXT_SECONDARY_OUTLINE,
  COMPONENTS_BUTTON_BORDER_SECONDARY_OUTLINE,
  COMPONENTS_BUTTON_BACKGROUND_TERTIARY,
  COMPONENTS_BUTTON_BACKGROUND_TERTIARY_HOVER,
  COMPONENTS_INPUT_BORDER_PRIMARY,
  COMPONENTS_MENU_BACKGROUND,
  COMPONENTS_MENU_ITEM_TEXT,
  COMPONENTS_MENU_ITEM_TEXT_ACTION,
  COMPONENTS_MENU_ITEM_BACKGROUND_HOVER,
  COMPONENTS_MENU_ITEM_BACKGROUND_ACTIVE,
  COMPONENTS_INPUT_BACKGROUND_PRIMARY,
};
