export const PINK_PINK_50 = '#fdecf2';
export const PINK_PINK_100 = '#f9c4d6';
export const PINK_PINK_200 = '#f6a7c2';
export const PINK_PINK_300 = '#f27fa6';
export const PINK_PINK_400 = '#f06695';
export const PINK_PINK_500 = '#ec407a';
export const PINK_PINK_600 = '#d73a6f';
export const PINK_PINK_700 = '#a82d57';
export const PINK_PINK_800 = '#822343';
export const PINK_PINK_900 = '#631b33';
export const GREEN_GREEN_50 = '#e6faf0';
export const GREEN_GREEN_100 = '#b0efd1';
export const GREEN_GREEN_200 = '#8ae7bb';
export const GREEN_GREEN_300 = '#54dc9d';
export const GREEN_GREEN_400 = '#33d589';
export const GREEN_GREEN_500 = '#00cb6c';
export const GREEN_GREEN_600 = '#00b962';
export const GREEN_GREEN_700 = '#00904d';
export const GREEN_GREEN_800 = '#00703b';
export const GREEN_GREEN_900 = '#00552d';
export const BLUE_GREEN_BLUE_GREEN_50 = '#e8fcf8';
export const BLUE_GREEN_BLUE_GREEN_100 = '#bef3e9';
export const BLUE_GREEN_BLUE_GREEN_200 = '#99e5d6';
export const BLUE_GREEN_BLUE_GREEN_300 = '#7ad3c1';
export const BLUE_GREEN_BLUE_GREEN_400 = '#35c4b0';
export const BLUE_GREEN_BLUE_GREEN_500 = '#00af9a';
export const BLUE_GREEN_BLUE_GREEN_600 = '#009b85';
export const BLUE_GREEN_BLUE_GREEN_700 = '#008371';
export const BLUE_GREEN_BLUE_GREEN_800 = '#006b5b';
export const BLUE_GREEN_BLUE_GREEN_900 = '#004437';
export const LIGHT_GRAY_LIGHT_GRAY_50 = '#fdfdff';
export const LIGHT_GRAY_LIGHT_GRAY_100 = '#fbfbfd';
export const LIGHT_GRAY_LIGHT_GRAY_200 = '#f9f9fb';
export const LIGHT_GRAY_LIGHT_GRAY_300 = '#f6f6f8';
export const LIGHT_GRAY_LIGHT_GRAY_400 = '#f4f4f6';
export const LIGHT_GRAY_LIGHT_GRAY_500 = '#f1f1f4';
export const LIGHT_GRAY_LIGHT_GRAY_600 = '#dbdbde';
export const LIGHT_GRAY_LIGHT_GRAY_700 = '#ababae';
export const LIGHT_GRAY_LIGHT_GRAY_800 = '#858587';
export const LIGHT_GRAY_LIGHT_GRAY_900 = '#656567';
export const GRAY_GRAY_50 = '#f0f2f4';
export const GRAY_GRAY_100 = '#d1d6dc';
export const GRAY_GRAY_200 = '#bbc2cb';
export const GRAY_GRAY_300 = '#9da7b4';
export const GRAY_GRAY_400 = '#8995a5';
export const GRAY_GRAY_500 = '#6c7b8f';
export const GRAY_GRAY_600 = '#627082';
export const GRAY_GRAY_700 = '#4d5b6e';
export const GRAY_GRAY_800 = '#2c3c52';
export const GRAY_GRAY_850 = '#243245';
export const GRAY_GRAY_900 = '#1f2d40';
export const GRAY_GRAY_950 = '#182230';
export const BASIC_WHITE = '#ffffff';
export const BASIC_BLACK = '#000000';
export const OTHER_YELLOW_500 = '#ffce00';
export const OTHER_YELLOW_600 = '#cca500';
export const OTHER_RED_400 = '#ff002e';
export const OTHER_RED_500 = '#d32f2f';
export const OTHER_RED_600 = '#c62828';
export const LOGO_LOGO_SYMBOL = {
  light: PINK_PINK_500,
  dark: GRAY_GRAY_50,
};
export const LOGO_LOGO_TEXT = {
  light: GRAY_GRAY_800,
  dark: GRAY_GRAY_50,
};
export const BUTTON_LINK_BUTTON_PRIMARY = {
  light: PINK_PINK_500,
  dark: PINK_PINK_400,
};
export const BUTTON_LINK_BUTTON_PRIMARY_HOVER = {
  light: PINK_PINK_600,
  dark: PINK_PINK_500,
};
export const BUTTON_LINK_BUTTON_PRIMARY_TEXT = {
  light: BASIC_WHITE,
  dark: GRAY_GRAY_950,
};
export const BUTTON_LINK_BUTTON_SECONDARY_HOVER = {
  light: LIGHT_GRAY_LIGHT_GRAY_200,
  dark: GRAY_GRAY_800,
};
export const BUTTON_LINK_BUTTON_SECONDARY_TEXT = {
  light: GRAY_GRAY_700,
  dark: GRAY_GRAY_100,
};
export const BUTTON_LINK_BUTTON_SECONDARY_TEXT_HOVER = {
  light: GRAY_GRAY_900,
  dark: GRAY_GRAY_100,
};
export const BUTTON_LINK_LINK_PINK = {
  light: PINK_PINK_500,
  dark: PINK_PINK_400,
};
export const ICON_ICON_PRIMARY = {
  light: GRAY_GRAY_600,
  dark: GRAY_GRAY_50,
};
export const ICON_ICON_PRIMARY_HOVER = {
  light: GRAY_GRAY_800,
  dark: BASIC_WHITE,
};
export const TEXT_PRIMARY = {
  light: GRAY_GRAY_800,
  dark: GRAY_GRAY_50,
};
export const TEXT_SECONDARY = {
  light: GRAY_GRAY_300,
  dark: GRAY_GRAY_200,
};
export const BACKGROUND_BG_MAIN_BAR = {
  light: BASIC_WHITE,
  dark: GRAY_GRAY_950,
};
export const BACKGROUND_BG_MAIN = {
  light: LIGHT_GRAY_LIGHT_GRAY_50,
  dark: GRAY_GRAY_900,
};
export const BACKGROUND_BG_MAIN_HOVER = {
  light: LIGHT_GRAY_LIGHT_GRAY_100,
  dark: GRAY_GRAY_850,
};
export const BACKGROUND_BG_MAIN_ACTIVE = {
  light: LIGHT_GRAY_LIGHT_GRAY_200,
  dark: GRAY_GRAY_800,
};
export const BACKGROUND_BG_ITEM = {
  light: LIGHT_GRAY_LIGHT_GRAY_300,
  dark: GRAY_GRAY_700,
};
export const BACKGROUND_BG_ITEM_HOVER = {
  light: LIGHT_GRAY_LIGHT_GRAY_400,
  dark: GRAY_GRAY_600,
};
export const BACKGROUND_BG_INPUT = {
  light: BASIC_WHITE,
  dark: GRAY_GRAY_900,
};
export const LINE_BORDER_LINE_PRIMARY = {
  light: GRAY_GRAY_50,
  dark: GRAY_GRAY_700,
};
export const LINE_BORDER_BORDER_PRIMARY = {
  light: GRAY_GRAY_100,
  dark: GRAY_GRAY_700,
};
export const LINE_BORDER_BORDER_PRIMARY_HOVER = {
  light: GRAY_GRAY_200,
  dark: GRAY_GRAY_600,
};
export const LINE_BORDER_BORDER_INPUT = {
  light: GRAY_GRAY_200,
  dark: GRAY_GRAY_600,
};
export const STATE_STATE_UNTRANSLATED = {
  light: GRAY_GRAY_200,
  dark: GRAY_GRAY_400,
};
export const STATE_STATE_TRANSLATED = {
  light: OTHER_YELLOW_500,
  dark: OTHER_YELLOW_600,
};
export const STATE_STATE_REVIEWED = {
  light: GREEN_GREEN_600,
  dark: GREEN_GREEN_700,
};

export const ALL_TOKENS = {
  PINK_PINK_50,
  PINK_PINK_100,
  PINK_PINK_200,
  PINK_PINK_300,
  PINK_PINK_400,
  PINK_PINK_500,
  PINK_PINK_600,
  PINK_PINK_700,
  PINK_PINK_800,
  PINK_PINK_900,
  GREEN_GREEN_50,
  GREEN_GREEN_100,
  GREEN_GREEN_200,
  GREEN_GREEN_300,
  GREEN_GREEN_400,
  GREEN_GREEN_500,
  GREEN_GREEN_600,
  GREEN_GREEN_700,
  GREEN_GREEN_800,
  GREEN_GREEN_900,
  BLUE_GREEN_BLUE_GREEN_50,
  BLUE_GREEN_BLUE_GREEN_100,
  BLUE_GREEN_BLUE_GREEN_200,
  BLUE_GREEN_BLUE_GREEN_300,
  BLUE_GREEN_BLUE_GREEN_400,
  BLUE_GREEN_BLUE_GREEN_500,
  BLUE_GREEN_BLUE_GREEN_600,
  BLUE_GREEN_BLUE_GREEN_700,
  BLUE_GREEN_BLUE_GREEN_800,
  BLUE_GREEN_BLUE_GREEN_900,
  LIGHT_GRAY_LIGHT_GRAY_50,
  LIGHT_GRAY_LIGHT_GRAY_100,
  LIGHT_GRAY_LIGHT_GRAY_200,
  LIGHT_GRAY_LIGHT_GRAY_300,
  LIGHT_GRAY_LIGHT_GRAY_400,
  LIGHT_GRAY_LIGHT_GRAY_500,
  LIGHT_GRAY_LIGHT_GRAY_600,
  LIGHT_GRAY_LIGHT_GRAY_700,
  LIGHT_GRAY_LIGHT_GRAY_800,
  LIGHT_GRAY_LIGHT_GRAY_900,
  GRAY_GRAY_50,
  GRAY_GRAY_100,
  GRAY_GRAY_200,
  GRAY_GRAY_300,
  GRAY_GRAY_400,
  GRAY_GRAY_500,
  GRAY_GRAY_600,
  GRAY_GRAY_700,
  GRAY_GRAY_800,
  GRAY_GRAY_850,
  GRAY_GRAY_900,
  GRAY_GRAY_950,
  BASIC_WHITE,
  BASIC_BLACK,
  OTHER_YELLOW_500,
  OTHER_YELLOW_600,
  OTHER_RED_400,
  OTHER_RED_500,
  OTHER_RED_600,
  LOGO_LOGO_SYMBOL,
  LOGO_LOGO_TEXT,
  BUTTON_LINK_BUTTON_PRIMARY,
  BUTTON_LINK_BUTTON_PRIMARY_HOVER,
  BUTTON_LINK_BUTTON_PRIMARY_TEXT,
  BUTTON_LINK_BUTTON_SECONDARY_HOVER,
  BUTTON_LINK_BUTTON_SECONDARY_TEXT,
  BUTTON_LINK_BUTTON_SECONDARY_TEXT_HOVER,
  BUTTON_LINK_LINK_PINK,
  ICON_ICON_PRIMARY,
  ICON_ICON_PRIMARY_HOVER,
  TEXT_PRIMARY,
  TEXT_SECONDARY,
  BACKGROUND_BG_MAIN_BAR,
  BACKGROUND_BG_MAIN,
  BACKGROUND_BG_MAIN_HOVER,
  BACKGROUND_BG_MAIN_ACTIVE,
  BACKGROUND_BG_ITEM,
  BACKGROUND_BG_ITEM_HOVER,
  BACKGROUND_BG_INPUT,
  LINE_BORDER_LINE_PRIMARY,
  LINE_BORDER_BORDER_PRIMARY,
  LINE_BORDER_BORDER_PRIMARY_HOVER,
  LINE_BORDER_BORDER_INPUT,
  STATE_STATE_UNTRANSLATED,
  STATE_STATE_TRANSLATED,
  STATE_STATE_REVIEWED,
};
