name: Download backend build
description: Download backend build from GitHub artifacts and decompress them

runs:
  using: composite
  steps:
    - name: Download backend build result
      uses: actions/download-artifact@v4
      with:
        name: backend
        path: ~/

    - name: Un-tar build results
      shell: bash
      run: |
        tar --zstd -xf ~/backend-api.tar.zst ./backend/api/build
        tar --zstd -xf ~/backend-app.tar.zst ./backend/app/build
        tar --zstd -xf ~/backend-data.tar.zst ./backend/data/build
        tar --zstd -xf ~/backend-misc.tar.zst ./backend/misc/build
        tar --zstd -xf ~/backend-security.tar.zst ./backend/security/build
        tar --zstd -xf ~/backend-testing.tar.zst ./backend/testing/build
        tar --zstd -xf ~/backend-ktlint.tar.zst ./backend/ktlint/build
        tar --zstd -xf ~/backend-development.tar.zst ./backend/development/build
        tar --zstd -xf ~/ee-backend-app.tar.zst ./ee/backend/app/build
        tar --zstd -xf ~/ee-backend-tests.tar.zst ./ee/backend/tests/build
        tar --zstd -xf ~/backend-email.tar.zst ./email/out
