package io.tolgee

import io.tolgee.testing.AbstractAuthorizedControllerTest

@ServerAppTestContextConfiguration
abstract class AbstractServerAppAuthorizedControllerTest : AbstractAuthorizedControllerTest()
