declare namespace DataCy {
    export type Value = 
        "add-box" |
        "api-keys-create-edit-dialog" |
        "api-keys-edit-button" |
        "api-keys-project-select-item" |
        "base-language-select" |
        "camera-button" |
        "create-project-language-add-button" |
        "dropzone" |
        "dropzone-inner" |
        "global-base-view-content" |
        "global-base-view-loading" |
        "global-base-view-title" |
        "global-confirmation-cancel" |
        "global-confirmation-confirm" |
        "global-confirmation-hard-mode-text-field" |
        "global-editor" |
        "global-form-cancel-button" |
        "global-form-save-button" |
        "global-form-select" |
        "global-list-item" |
        "global-list-item-text" |
        "global-list-items" |
        "global-list-pagination" |
        "global-list-search" |
        "global-paginated-list" |
        "global-plus-button" |
        "global-search-field" |
        "global-snackbars" |
        "global-user-menu-button" |
        "import-conflict-resolution-dialog" |
        "import-conflicts-not-resolved-dialog" |
        "import-conflicts-not-resolved-dialog-cancel-button" |
        "import-conflicts-not-resolved-dialog-resolve-button" |
        "import-file-error" |
        "import-file-error-collapse-button" |
        "import-file-error-more-less-button" |
        "import-file-input" |
        "import-file-issues-button" |
        "import-file-issues-dialog" |
        "import-resolution-dialog-accept-imported-button" |
        "import-resolution-dialog-accept-old-button" |
        "import-resolution-dialog-close-button" |
        "import-resolution-dialog-conflict-count" |
        "import-resolution-dialog-data-row" |
        "import-resolution-dialog-existing-translation" |
        "import-resolution-dialog-key-name" |
        "import-resolution-dialog-new-translation" |
        "import-resolution-dialog-resolved-count" |
        "import-resolution-dialog-show-resolved-switch" |
        "import-resolution-dialog-translation-check" |
        "import-resolution-dialog-translation-loading" |
        "import-resolution-translation-expand-button" |
        "import-result-delete-language-button" |
        "import-result-file-cell" |
        "import-result-file-warnings" |
        "import-result-language-menu-cell" |
        "import-result-resolve-button" |
        "import-result-resolved-conflicts-cell" |
        "import-result-row" |
        "import-result-show-all-translations-button" |
        "import-result-total-count-cell" |
        "import-row-language-select-clear-button" |
        "import-row-language-select-form-control" |
        "import-show-data-dialog" |
        "import_apply_import_button" |
        "import_cancel_import_button" |
        "invite-generate-button" |
        "invite-generate-input-code" |
        "language-delete-button" |
        "language-modify-form" |
        "languages-create-autocomplete-field" |
        "languages-create-autocomplete-suggested-option" |
        "languages-create-cancel-prepared-button" |
        "languages-create-customize-button" |
        "languages-create-submit-button" |
        "languages-flag-selector-open-button" |
        "languages-modify-apply-button" |
        "languages-modify-cancel-button" |
        "languages-prepared-language-box" |
        "leave-organization-button" |
        "organization-address-part-field" |
        "organization-delete-button" |
        "organization-description-field" |
        "organization-invitation-cancel-button" |
        "organization-invitation-generate-button" |
        "organization-invitation-role-select" |
        "organization-invitations-generated-field" |
        "organization-members-leave-button" |
        "organization-members-remove-user-button" |
        "organization-name-field" |
        "organization-role-menu" |
        "organization-role-menu-button" |
        "organization-role-select-item" |
        "organization-settings-button" |
        "organization-side-menu" |
        "organizations-user-email" |
        "organizations-user-name" |
        "permission-select-item" |
        "permissions-menu" |
        "permissions-menu-button" |
        "permissions-revoke-button" |
        "project-list-owner" |
        "project-menu-items" |
        "project-name-field" |
        "project-owner-select" |
        "project-owner-select-item" |
        "project-settings-button" |
        "project-settings-languages-list-edit-button" |
        "project-settings-languages-list-item" |
        "screenshot-box" |
        "translations-add-button" |
        "translations-add-key-dialog" |
        "translations-add-key-field" |
        "translations-cell-cancel-button" |
        "translations-cell-data" |
        "translations-cell-edit-button" |
        "translations-cell-save-button" |
        "translations-cell-screenshots-button" |
        "translations-delete-button" |
        "translations-language-select-form-control" |
        "translations-row-checkbox" |
        "translations-table-cell" |
        "user-account-side-menu" |
        "user-organizations-settings-subtitle-link"
}