declare namespace DataCy {
    export type Value = 
        "translations-editable-cell" |
        "translations-editable-cell-editing" |
        "translations-delete-button" |
        "camera-button" |
        "dropzone" |
        "add-box" |
        "screenshot-box" |
        "translations-add-key-dialog" |
        "translations-add-key-field" |
        "translations-row-checkbox" |
        "global-confirmation-hard-mode-text-field" |
        "global-confirmation-cancel" |
        "global-confirmation-confirm" |
        "global-plus-button" |
        "global-form-cancel-button" |
        "global-form-save-button" |
        "global-field-array-minus-button" |
        "global-field-array-plus-button" |
        "global-field-array-add-button" |
        "global-form-select" |
        "global-list-item" |
        "simple-hateoas-list" |
        "global-list-item" |
        "global-paginated-list" |
        "global-list-search" |
        "global-list-pagination" |
        "global-base-view-title" |
        "permission-select-item" |
        "permissions-menu-button" |
        "permissions-menu" |
        "organization-invitation-generate-button" |
        "organization-invitation-role-select" |
        "organization-invitations-generated-field" |
        "organization-invitation-cancel-button" |
        "global-list-item-text" |
        "leave-organization-button" |
        "organization-settings-button" |
        "organizations-user-name" |
        "organizations-user-email" |
        "organization-members-leave-button" |
        "organization-delete-button" |
        "organization-name-field" |
        "organization-address-part-field" |
        "organization-description-field" |
        "organization-members-remove-user-button" |
        "organization-role-menu-button" |
        "organization-role-menu" |
        "organization-role-select-item" |
        "organization-side-menu" |
        "repository-list-owner" |
        "repository-settings-button" |
        "repository-menu-items" |
        "permissions-revoke-button" |
        "repository-name-field" |
        "repository-language-name-field" |
        "repository-language-abbreviation-field" |
        "repository-owner-select-item" |
        "repository-owner-select" |
        "user-account-side-menu" |
        "global-snackbars"
}