/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v2/organizations/{organizationId}/billing/update-subscription": {
    put: operations["updateSubscription"];
  };
  "/v2/organizations/{organizationId}/billing/self-hosted-ee/refresh-subscriptions": {
    put: operations["refreshSelfHostedEeSubscriptions"];
  };
  "/v2/organizations/{organizationId}/billing/refresh-subscription": {
    put: operations["refresh"];
  };
  "/v2/organizations/{organizationId}/billing/prepare-update-subscription": {
    put: operations["prepareUpdateSubscription"];
  };
  "/v2/organizations/{organizationId}/billing/cancel-subscription": {
    /** When applied, current subscription will be cancelled at the period end. */
    put: operations["cancelSubscription"];
  };
  "/v2/administration/billing/self-hosted-ee-plans/{planId}": {
    get: operations["getPlan"];
    put: operations["updatePlan"];
    delete: operations["deletePlan"];
  };
  "/v2/administration/billing/cloud-plans/{planId}": {
    get: operations["getPlan_1"];
    put: operations["updatePlan_1"];
    delete: operations["deletePlan_1"];
  };
  "/v2/organizations/{organizationId}/billing/subscribe": {
    post: operations["subscribe"];
  };
  "/v2/organizations/{organizationId}/billing/self-hosted-ee/subscriptions": {
    get: operations["getSelfHostedEeSubscriptions"];
    post: operations["setupEeSubscription"];
  };
  "/v2/organizations/{organizationId}/billing/self-hosted-ee/subscribe-free": {
    post: operations["setupFreeEeSubscription"];
  };
  "/v2/organizations/{organizationId}/billing/buy-more-credits": {
    post: operations["getBuyMoreCreditsCheckoutSessionUrl"];
  };
  "/v2/administration/billing/self-hosted-ee-plans": {
    get: operations["getPlans_1"];
    post: operations["create"];
  };
  "/v2/administration/billing/cloud-plans": {
    get: operations["getPlans_2"];
    post: operations["create_1"];
  };
  "/v2/public/billing/plans": {
    get: operations["getPlans"];
  };
  "/v2/public/billing/mt-credit-prices": {
    get: operations["getMtCreditPrices"];
  };
  "/v2/organizations/{organizationId}/billing/subscription": {
    get: operations["getSubscription"];
  };
  "/v2/organizations/{organizationId}/billing/self-hosted-ee/subscriptions/{subscriptionId}/expected-usage": {
    get: operations["getExpectedUsage"];
  };
  "/v2/organizations/{organizationId}/billing/self-hosted-ee/plans": {
    get: operations["getSelfHostedPlans"];
  };
  "/v2/organizations/{organizationId}/billing/plans": {
    /** Returns list of available cloud plans for specific organization.) */
    get: operations["getCloudPlans"];
  };
  "/v2/organizations/{organizationId}/billing/invoices": {
    get: operations["getInvoices"];
  };
  "/v2/organizations/{organizationId}/billing/invoices/{invoiceId}/usage": {
    get: operations["getUsage"];
  };
  "/v2/organizations/{organizationId}/billing/invoices/{invoiceId}/usage/{type}.csv": {
    /** Returns CSV file with usage detail for each time period and it's usage. */
    get: operations["getUsageDetail"];
  };
  "/v2/organizations/{organizationId}/billing/invoices/{invoiceId}/pdf": {
    get: operations["getInvoicePdf"];
  };
  "/v2/organizations/{organizationId}/billing/expected-usage": {
    get: operations["getExpectedUsage_1"];
  };
  "/v2/organizations/{organizationId}/billing/customer-portal": {
    get: operations["goToCustomerPortal"];
  };
  "/v2/organizations/{organizationId}/billing/billing-info": {
    get: operations["getBillingInfo"];
  };
  "/v2/administration/billing/stripe-products": {
    get: operations["getStripeProducts"];
  };
  "/v2/administration/billing/self-hosted-ee-plans/{planId}/organizations": {
    get: operations["getPlanOrganizations"];
  };
  "/v2/administration/billing/features": {
    get: operations["getAllFeatures"];
  };
  "/v2/administration/billing/cloud-plans/{planId}/organizations": {
    get: operations["getPlanOrganizations_1"];
  };
  "/v2/organizations/{organizationId}/billing/self-hosted-ee/subscriptions/{subscriptionId}": {
    delete: operations["cancelEeSubscription"];
  };
}

export interface components {
  schemas: {
    ErrorResponseTyped: {
      code:
        | "unauthenticated"
        | "api_access_forbidden"
        | "api_key_not_found"
        | "invalid_api_key"
        | "invalid_project_api_key"
        | "project_api_key_expired"
        | "bad_credentials"
        | "mfa_enabled"
        | "invalid_otp_code"
        | "mfa_not_enabled"
        | "can_not_revoke_own_permissions"
        | "data_corrupted"
        | "invitation_code_does_not_exist_or_expired"
        | "language_tag_exists"
        | "language_name_exists"
        | "language_not_found"
        | "operation_not_permitted"
        | "registrations_not_allowed"
        | "project_not_found"
        | "resource_not_found"
        | "scope_not_found"
        | "key_exists"
        | "third_party_auth_error_message"
        | "third_party_auth_no_email"
        | "third_party_auth_no_sub"
        | "third_party_auth_unknown_error"
        | "email_already_verified"
        | "third_party_unauthorized"
        | "third_party_google_workspace_mismatch"
        | "username_already_exists"
        | "username_or_password_invalid"
        | "user_already_has_permissions"
        | "user_already_has_role"
        | "user_not_found"
        | "file_not_image"
        | "file_too_big"
        | "invalid_timestamp"
        | "email_not_verified"
        | "missing_callback_url"
        | "invalid_jwt_token"
        | "expired_jwt_token"
        | "general_jwt_error"
        | "cannot_find_suitable_address_part"
        | "address_part_not_unique"
        | "user_is_not_member_of_organization"
        | "organization_has_no_other_owner"
        | "user_has_no_project_access"
        | "user_is_organization_owner"
        | "cannot_set_your_own_permissions"
        | "user_is_organization_member"
        | "property_not_mutable"
        | "import_language_not_from_project"
        | "existing_language_not_selected"
        | "conflict_is_not_resolved"
        | "language_already_selected"
        | "cannot_parse_file"
        | "could_not_resolve_property"
        | "cannot_add_more_then_100_languages"
        | "no_languages_provided"
        | "language_with_base_language_tag_not_found"
        | "language_not_from_project"
        | "namespace_not_from_project"
        | "cannot_delete_base_language"
        | "key_not_from_project"
        | "max_screenshots_exceeded"
        | "translation_not_from_project"
        | "can_edit_only_own_comment"
        | "request_parse_error"
        | "filter_by_value_state_not_valid"
        | "import_has_expired"
        | "tag_not_from_project"
        | "translation_text_too_long"
        | "invalid_recaptcha_token"
        | "cannot_leave_owning_project"
        | "cannot_leave_project_with_organization_role"
        | "dont_have_direct_permissions"
        | "tag_too_log"
        | "too_many_uploaded_images"
        | "one_or_more_images_not_found"
        | "screenshot_not_of_key"
        | "service_not_found"
        | "too_many_requests"
        | "translation_not_found"
        | "out_of_credits"
        | "key_not_found"
        | "organization_not_found"
        | "cannot_find_base_language"
        | "base_language_not_found"
        | "no_exported_result"
        | "cannot_set_your_own_role"
        | "only_translate_review_or_view_permission_accepts_view_languages"
        | "oauth2_token_url_not_set"
        | "oauth2_user_url_not_set"
        | "email_already_invited_or_member"
        | "price_not_found"
        | "invoice_not_from_organization"
        | "invoice_not_found"
        | "plan_not_found"
        | "plan_not_available_any_more"
        | "no_auto_translation_method"
        | "cannot_translate_base_language"
        | "pat_not_found"
        | "invalid_pat"
        | "pat_expired"
        | "operation_unavailable_for_account_type"
        | "validation_email_is_not_valid"
        | "current_password_required"
        | "cannot_create_organization"
        | "wrong_current_password"
        | "wrong_param_type"
        | "expired_super_jwt_token"
        | "cannot_delete_your_own_account"
        | "cannot_sort_by_this_column"
        | "namespace_not_found"
        | "namespace_exists"
        | "invalid_authentication_method"
        | "unknown_sort_property"
        | "only_review_permission_accepts_state_change_languages"
        | "only_translate_or_review_permission_accepts_translate_languages"
        | "cannot_set_language_permissions_for_admin_scope"
        | "cannot_set_view_languages_without_translations_view_scope"
        | "cannot_set_translate_languages_without_translations_edit_scope"
        | "cannot_set_state_change_languages_without_translations_state_edit_scope"
        | "language_not_permitted"
        | "scopes_has_to_be_set"
        | "set_exactly_one_of_scopes_or_type"
        | "translation_exists"
        | "import_keys_error"
        | "provide_only_one_of_screenshots_and_screenshot_uploaded_image_ids"
        | "multiple_projects_not_supported"
        | "plan_translation_limit_exceeded"
        | "feature_not_enabled"
        | "license_key_not_found"
        | "cannot_set_view_languages_without_for_level_based_permissions"
        | "cannot_set_different_translate_and_state_change_languages_for_level_based_permissions"
        | "cannot_disable_your_own_account"
        | "subscription_not_found"
        | "invoice_does_not_have_usage"
        | "customer_not_found"
        | "subscription_not_active"
        | "organization_already_subscribed"
        | "organization_not_subscribed"
        | "license_key_used_by_another_instance"
        | "translation_spending_limit_exceeded"
        | "credit_spending_limit_exceeded"
        | "seats_spending_limit_exceeded"
        | "this_instance_is_already_licensed"
        | "big_meta_not_from_project"
        | "mt_service_not_enabled"
        | "project_not_selected"
        | "organization_not_selected"
        | "plan_has_subscribers"
        | "translation_failed"
        | "batch_job_not_found"
        | "key_exists_in_namespace"
        | "tag_is_blank"
        | "execution_failed_on_management_error"
        | "translation_api_rate_limit"
        | "cannot_finalize_activity"
        | "formality_not_supported_by_service"
        | "language_not_supported_by_service"
        | "rate_limited"
        | "pat_access_not_allowed"
        | "pak_access_not_allowed"
        | "cannot_modify_disabled_translation"
        | "azure_config_required"
        | "s3_config_required"
        | "content_storage_config_required"
        | "content_storage_test_failed"
        | "content_storage_config_invalid"
        | "invalid_connection_string"
        | "cannot_create_azure_storage_client"
        | "s3_access_key_required"
        | "azure_connection_string_required"
        | "s3_secret_key_required"
        | "cannot_store_file_to_content_storage"
        | "unexpected_error_while_publishing_to_content_storage"
        | "webhook_responded_with_non_200_status"
        | "unexpected_error_while_executing_webhook"
        | "content_storage_is_in_use"
        | "cannot_set_state_for_missing_translation"
        | "no_project_id_provided"
        | "license_key_not_provided"
        | "subscription_already_canceled"
        | "user_is_subscribed_to_paid_plan"
        | "cannot_create_free_plan_without_fixed_type"
        | "cannot_modify_plan_free_status"
        | "key_id_not_provided"
        | "free_self_hosted_seat_limit_exceeded"
        | "advanced_params_not_supported"
        | "plural_forms_not_found_for_language"
        | "nested_plurals_not_supported"
        | "message_is_not_plural"
        | "content_outside_plural_forms"
        | "invalid_plural_form"
        | "multiple_plurals_not_supported"
        | "custom_values_json_too_long"
        | "unsupported_po_message_format"
        | "plural_forms_data_loss"
        | "current_user_does_not_own_image"
        | "user_cannot_view_this_organization"
        | "user_is_not_owner_of_organization"
        | "pak_created_for_different_project"
        | "custom_slug_is_only_applicable_for_custom_storage"
        | "invalid_slug_format"
        | "batch_job_cancellation_timeout"
        | "import_failed"
        | "cannot_add_more_then_1000_languages"
        | "no_data_to_import"
        | "multiple_namespaces_mapped_to_single_file"
        | "multiple_mappings_for_same_file_language_name"
        | "multiple_mappings_for_null_file_language_name"
        | "too_many_mappings_for_file"
        | "missing_placeholder_in_template"
        | "tag_not_found"
        | "cannot_parse_encrypted_slack_login_data"
        | "slack_workspace_not_found"
        | "cannot_fetch_user_details_from_slack"
        | "slack_missing_scope"
        | "slack_not_connected_to_your_account"
        | "slack_invalid_command"
        | "slack_not_subscribed_yet"
        | "slack_connection_failed"
        | "tolgee_account_already_connected"
        | "slack_not_configured"
        | "slack_workspace_already_connected"
        | "slack_connection_error"
        | "email_verification_code_not_valid"
        | "cannot_subscribe_to_free_plan"
        | "plan_auto_assignment_only_for_free_plans"
        | "plan_auto_assignment_only_for_private_plans"
        | "plan_auto_assignment_organization_ids_not_in_for_organization_ids"
        | "task_not_found"
        | "task_not_finished"
        | "task_not_open";
      params?: { [key: string]: unknown }[];
    };
    ErrorResponseBody: {
      code: string;
      params?: { [key: string]: unknown }[];
    };
    UpdateSubscriptionRequest: {
      token: string;
    };
    CollectionModelSelfHostedEeSubscriptionModel: {
      _embedded?: {
        subscriptions?: components["schemas"]["SelfHostedEeSubscriptionModel"][];
      };
    };
    PlanIncludedUsageModel: {
      /** Format: int64 */
      seats: number;
      /** Format: int64 */
      translationSlots: number;
      /** Format: int64 */
      translations: number;
      /** Format: int64 */
      mtCredits: number;
    };
    PlanPricesModel: {
      perSeat: number;
      perThousandTranslations?: number;
      perThousandMtCredits?: number;
      subscriptionMonthly: number;
      subscriptionYearly: number;
    };
    SelfHostedEePlanModel: {
      /** Format: int64 */
      id: number;
      name: string;
      public: boolean;
      enabledFeatures: (
        | "GRANULAR_PERMISSIONS"
        | "PRIORITIZED_FEATURE_REQUESTS"
        | "PREMIUM_SUPPORT"
        | "DEDICATED_SLACK_CHANNEL"
        | "ASSISTED_UPDATES"
        | "DEPLOYMENT_ASSISTANCE"
        | "BACKUP_CONFIGURATION"
        | "TEAM_TRAINING"
        | "ACCOUNT_MANAGER"
        | "STANDARD_SUPPORT"
        | "PROJECT_LEVEL_CONTENT_STORAGES"
        | "WEBHOOKS"
        | "MULTIPLE_CONTENT_DELIVERY_CONFIGS"
        | "AI_PROMPT_CUSTOMIZATION"
        | "SLACK_INTEGRATION"
        | "TASKS"
      )[];
      prices: components["schemas"]["PlanPricesModel"];
      includedUsage: components["schemas"]["PlanIncludedUsageModel"];
      hasYearlyPrice: boolean;
      free: boolean;
    };
    SelfHostedEeSubscriptionModel: {
      /** Format: int64 */
      id: number;
      /** Format: int64 */
      currentPeriodStart?: number;
      /** Format: int64 */
      currentPeriodEnd?: number;
      currentBillingPeriod: "MONTHLY" | "YEARLY";
      /** Format: int64 */
      createdAt: number;
      plan: components["schemas"]["SelfHostedEePlanModel"];
      status:
        | "ACTIVE"
        | "CANCELED"
        | "PAST_DUE"
        | "UNPAID"
        | "ERROR"
        | "KEY_USED_BY_ANOTHER_INSTANCE";
      licenseKey?: string;
      estimatedCosts?: number;
    };
    CloudPlanModel: {
      /** Format: int64 */
      id: number;
      name: string;
      free: boolean;
      enabledFeatures: (
        | "GRANULAR_PERMISSIONS"
        | "PRIORITIZED_FEATURE_REQUESTS"
        | "PREMIUM_SUPPORT"
        | "DEDICATED_SLACK_CHANNEL"
        | "ASSISTED_UPDATES"
        | "DEPLOYMENT_ASSISTANCE"
        | "BACKUP_CONFIGURATION"
        | "TEAM_TRAINING"
        | "ACCOUNT_MANAGER"
        | "STANDARD_SUPPORT"
        | "PROJECT_LEVEL_CONTENT_STORAGES"
        | "WEBHOOKS"
        | "MULTIPLE_CONTENT_DELIVERY_CONFIGS"
        | "AI_PROMPT_CUSTOMIZATION"
        | "SLACK_INTEGRATION"
        | "TASKS"
      )[];
      type: "PAY_AS_YOU_GO" | "FIXED" | "SLOTS_FIXED";
      prices: components["schemas"]["PlanPricesModel"];
      includedUsage: components["schemas"]["PlanIncludedUsageModel"];
      hasYearlyPrice: boolean;
      public: boolean;
    };
    CloudSubscriptionModel: {
      /** Format: int64 */
      organizationId: number;
      plan: components["schemas"]["CloudPlanModel"];
      /** Format: int64 */
      currentPeriodStart?: number;
      /** Format: int64 */
      currentPeriodEnd?: number;
      currentBillingPeriod?: "MONTHLY" | "YEARLY";
      cancelAtPeriodEnd: boolean;
      estimatedCosts?: number;
      /** Format: int64 */
      createdAt: number;
    };
    UpdateSubscriptionPrepareRequest: {
      /**
       * Format: int64
       * @description Id of the subscription plan
       */
      planId: number;
      period: "MONTHLY" | "YEARLY";
    };
    SubscriptionUpdatePreviewItem: {
      description: string;
      amount: number;
      taxRate: number;
    };
    SubscriptionUpdatePreviewModel: {
      items: components["schemas"]["SubscriptionUpdatePreviewItem"][];
      total: number;
      amountDue: number;
      updateToken: string;
      /** Format: int64 */
      prorationDate: number;
      endingBalance: number;
    };
    PlanIncludedUsageRequest: {
      /** Format: int64 */
      seats: number;
      /** Format: int64 */
      translations: number;
      /** Format: int64 */
      mtCredits: number;
    };
    PlanPricesRequest: {
      perSeat: number;
      perThousandTranslations?: number;
      perThousandMtCredits?: number;
      subscriptionMonthly: number;
      subscriptionYearly: number;
    };
    SelfHostedEePlanRequest: {
      name: string;
      enabledFeatures: (
        | "GRANULAR_PERMISSIONS"
        | "PRIORITIZED_FEATURE_REQUESTS"
        | "PREMIUM_SUPPORT"
        | "DEDICATED_SLACK_CHANNEL"
        | "ASSISTED_UPDATES"
        | "DEPLOYMENT_ASSISTANCE"
        | "BACKUP_CONFIGURATION"
        | "TEAM_TRAINING"
        | "ACCOUNT_MANAGER"
        | "STANDARD_SUPPORT"
        | "PROJECT_LEVEL_CONTENT_STORAGES"
        | "WEBHOOKS"
        | "MULTIPLE_CONTENT_DELIVERY_CONFIGS"
        | "AI_PROMPT_CUSTOMIZATION"
        | "SLACK_INTEGRATION"
        | "TASKS"
      )[];
      prices: components["schemas"]["PlanPricesRequest"];
      includedUsage: components["schemas"]["PlanIncludedUsageRequest"];
      public: boolean;
      stripeProductId?: string;
      /** Format: date-time */
      notAvailableBefore?: string;
      /** Format: date-time */
      availableUntil?: string;
      /** Format: date-time */
      usableUntil?: string;
      forOrganizationIds: number[];
      free: boolean;
    };
    SelfHostedEePlanAdministrationModel: {
      /** Format: int64 */
      id: number;
      name: string;
      public: boolean;
      enabledFeatures: (
        | "GRANULAR_PERMISSIONS"
        | "PRIORITIZED_FEATURE_REQUESTS"
        | "PREMIUM_SUPPORT"
        | "DEDICATED_SLACK_CHANNEL"
        | "ASSISTED_UPDATES"
        | "DEPLOYMENT_ASSISTANCE"
        | "BACKUP_CONFIGURATION"
        | "TEAM_TRAINING"
        | "ACCOUNT_MANAGER"
        | "STANDARD_SUPPORT"
        | "PROJECT_LEVEL_CONTENT_STORAGES"
        | "WEBHOOKS"
        | "MULTIPLE_CONTENT_DELIVERY_CONFIGS"
        | "AI_PROMPT_CUSTOMIZATION"
        | "SLACK_INTEGRATION"
        | "TASKS"
      )[];
      prices: components["schemas"]["PlanPricesModel"];
      includedUsage: components["schemas"]["PlanIncludedUsageModel"];
      hasYearlyPrice: boolean;
      free: boolean;
      stripeProductId: string;
      forOrganizationIds: number[];
    };
    CloudPlanRequest: {
      name: string;
      free: boolean;
      enabledFeatures: (
        | "GRANULAR_PERMISSIONS"
        | "PRIORITIZED_FEATURE_REQUESTS"
        | "PREMIUM_SUPPORT"
        | "DEDICATED_SLACK_CHANNEL"
        | "ASSISTED_UPDATES"
        | "DEPLOYMENT_ASSISTANCE"
        | "BACKUP_CONFIGURATION"
        | "TEAM_TRAINING"
        | "ACCOUNT_MANAGER"
        | "STANDARD_SUPPORT"
        | "PROJECT_LEVEL_CONTENT_STORAGES"
        | "WEBHOOKS"
        | "MULTIPLE_CONTENT_DELIVERY_CONFIGS"
        | "AI_PROMPT_CUSTOMIZATION"
        | "SLACK_INTEGRATION"
        | "TASKS"
      )[];
      type: "PAY_AS_YOU_GO" | "FIXED" | "SLOTS_FIXED";
      prices: components["schemas"]["PlanPricesRequest"];
      includedUsage: components["schemas"]["PlanIncludedUsageRequest"];
      public: boolean;
      stripeProductId: string;
      /** Format: date-time */
      notAvailableBefore?: string;
      /** Format: date-time */
      availableUntil?: string;
      /** Format: date-time */
      usableUntil?: string;
      forOrganizationIds: number[];
      autoAssignOrganizationIds: number[];
    };
    CloudPlanAdministrationModel: {
      /** Format: int64 */
      id: number;
      name: string;
      free: boolean;
      enabledFeatures: (
        | "GRANULAR_PERMISSIONS"
        | "PRIORITIZED_FEATURE_REQUESTS"
        | "PREMIUM_SUPPORT"
        | "DEDICATED_SLACK_CHANNEL"
        | "ASSISTED_UPDATES"
        | "DEPLOYMENT_ASSISTANCE"
        | "BACKUP_CONFIGURATION"
        | "TEAM_TRAINING"
        | "ACCOUNT_MANAGER"
        | "STANDARD_SUPPORT"
        | "PROJECT_LEVEL_CONTENT_STORAGES"
        | "WEBHOOKS"
        | "MULTIPLE_CONTENT_DELIVERY_CONFIGS"
        | "AI_PROMPT_CUSTOMIZATION"
        | "SLACK_INTEGRATION"
        | "TASKS"
      )[];
      type: "PAY_AS_YOU_GO" | "FIXED" | "SLOTS_FIXED";
      prices: components["schemas"]["PlanPricesModel"];
      includedUsage: components["schemas"]["PlanIncludedUsageModel"];
      hasYearlyPrice: boolean;
      public: boolean;
      stripeProductId: string;
      forOrganizationIds: number[];
    };
    CloudSubscribeRequest: {
      /**
       * Format: int64
       * @description Id of the subscription plan
       */
      planId: number;
      period: "MONTHLY" | "YEARLY";
    };
    SubscribeModel: {
      url: string;
    };
    SelfHostedEeSubscribeRequest: {
      /**
       * Format: int64
       * @description Id of the subscription plan
       */
      planId: number;
      period: "MONTHLY" | "YEARLY";
    };
    SelfHostedEeFreeSubscribeRequest: {
      /**
       * Format: int64
       * @description Id of the subscription plan
       */
      planId: number;
    };
    BuyMoreCreditsRequest: {
      /** Format: int64 */
      priceId: number;
      /** Format: int64 */
      amount: number;
    };
    BuyMoreCreditsModel: {
      url: string;
    };
    CollectionModelCloudPlanModel: {
      _embedded?: {
        plans?: components["schemas"]["CloudPlanModel"][];
      };
    };
    CollectionModelMtCreditsPriceModel: {
      _embedded?: {
        prices?: components["schemas"]["MtCreditsPriceModel"][];
      };
    };
    MtCreditsPriceModel: {
      /** Format: int64 */
      id: number;
      price: number;
      /** Format: int64 */
      amount: number;
    };
    AverageProportionalUsageItemModel: {
      total: number;
      unusedQuantity: number;
      usedQuantity: number;
      usedQuantityOverPlan: number;
    };
    SumUsageItemModel: {
      total: number;
      /** Format: int64 */
      unusedQuantity: number;
      /** Format: int64 */
      usedQuantity: number;
      /** Format: int64 */
      usedQuantityOverPlan: number;
    };
    UsageModel: {
      subscriptionPrice?: number;
      /** @description Relevant for invoices only. When there are applied stripe credits, we need to reduce the total price by this amount. */
      appliedStripeCredits?: number;
      seats: components["schemas"]["AverageProportionalUsageItemModel"];
      translations: components["schemas"]["AverageProportionalUsageItemModel"];
      credits?: components["schemas"]["SumUsageItemModel"];
      total: number;
    };
    CollectionModelSelfHostedEePlanModel: {
      _embedded?: {
        plans?: components["schemas"]["SelfHostedEePlanModel"][];
      };
    };
    InvoiceModel: {
      /** Format: int64 */
      id: number;
      /** @description The number on the invoice */
      number: string;
      /** Format: int64 */
      createdAt: number;
      /** @description The Total amount with tax */
      total: number;
      taxRatePercentage?: number;
      /** @description Whether pdf is ready to download. If not, wait around few minutes until it's generated. */
      pdfReady: boolean;
      hasUsage: boolean;
    };
    PageMetadata: {
      /** Format: int64 */
      size?: number;
      /** Format: int64 */
      totalElements?: number;
      /** Format: int64 */
      totalPages?: number;
      /** Format: int64 */
      number?: number;
    };
    PagedModelInvoiceModel: {
      _embedded?: {
        invoices?: components["schemas"]["InvoiceModel"][];
      };
      page?: components["schemas"]["PageMetadata"];
    };
    GoToCustomerPortalModel: {
      url: string;
    };
    BillingInfoModel: {
      name?: string;
      street?: string;
      street2?: string;
      city?: string;
      zip?: string;
      state?: string;
      countryIso?: string;
      registrationNo?: string;
      vatNo?: string;
      email?: string;
    };
    CollectionModelStripeProductModel: {
      _embedded?: {
        stripeProducts?: components["schemas"]["StripeProductModel"][];
      };
    };
    StripeProductModel: {
      id: string;
      name: string;
      /** Format: int64 */
      created: number;
    };
    CollectionModelSelfHostedEePlanAdministrationModel: {
      _embedded?: {
        plans?: components["schemas"]["SelfHostedEePlanAdministrationModel"][];
      };
    };
    /** @example Links to avatar images */
    Avatar: {
      large: string;
      thumbnail: string;
    };
    PagedModelSimpleOrganizationModel: {
      _embedded?: {
        organizations?: components["schemas"]["SimpleOrganizationModel"][];
      };
      page?: components["schemas"]["PageMetadata"];
    };
    PermissionModel: {
      /**
       * @description Granted scopes to the user. When user has type permissions, this field contains permission scopes of the type.
       * @example KEYS_EDIT,TRANSLATIONS_VIEW
       */
      scopes: (
        | "translations.view"
        | "translations.edit"
        | "keys.edit"
        | "screenshots.upload"
        | "screenshots.delete"
        | "screenshots.view"
        | "activity.view"
        | "languages.edit"
        | "admin"
        | "project.edit"
        | "members.view"
        | "members.edit"
        | "translation-comments.add"
        | "translation-comments.edit"
        | "translation-comments.set-state"
        | "translations.state-edit"
        | "keys.view"
        | "keys.delete"
        | "keys.create"
        | "batch-jobs.view"
        | "batch-jobs.cancel"
        | "translations.batch-by-tm"
        | "translations.batch-machine"
        | "content-delivery.manage"
        | "content-delivery.publish"
        | "webhooks.manage"
        | "tasks.view"
        | "tasks.edit"
      )[];
      /** @description The user's permission type. This field is null if uses granular permissions */
      type?: "NONE" | "VIEW" | "TRANSLATE" | "REVIEW" | "EDIT" | "MANAGE";
      /**
       * @deprecated
       * @description Deprecated (use translateLanguageIds).
       *
       * List of languages current user has TRANSLATE permission to. If null, all languages edition is permitted.
       * @example 200001,200004
       */
      permittedLanguageIds?: number[];
      /**
       * @description List of languages user can translate to. If null, all languages editing is permitted.
       * @example 200001,200004
       */
      translateLanguageIds?: number[];
      /**
       * @description List of languages user can view. If null, all languages view is permitted.
       * @example 200001,200004
       */
      viewLanguageIds?: number[];
      /**
       * @description List of languages user can change state to. If null, changing state of all language values is permitted.
       * @example 200001,200004
       */
      stateChangeLanguageIds?: number[];
    };
    SimpleOrganizationModel: {
      /** Format: int64 */
      id: number;
      /** @example Beautiful organization */
      name: string;
      /** @example btforg */
      slug: string;
      /** @example This is a beautiful organization full of beautiful and clever people */
      description?: string;
      basePermissions: components["schemas"]["PermissionModel"];
      avatar?: components["schemas"]["Avatar"];
    };
    CollectionModelCloudPlanAdministrationModel: {
      _embedded?: {
        plans?: components["schemas"]["CloudPlanAdministrationModel"][];
      };
    };
  };
}

export interface operations {
  updateSubscription: {
    parameters: {
      path: {
        organizationId: number;
      };
    };
    responses: {
      /** OK */
      200: unknown;
      /** Bad Request */
      400: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateSubscriptionRequest"];
      };
    };
  };
  refreshSelfHostedEeSubscriptions: {
    parameters: {
      path: {
        organizationId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["CollectionModelSelfHostedEeSubscriptionModel"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
    };
  };
  refresh: {
    parameters: {
      path: {
        organizationId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["CloudSubscriptionModel"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
    };
  };
  prepareUpdateSubscription: {
    parameters: {
      path: {
        organizationId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["SubscriptionUpdatePreviewModel"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateSubscriptionPrepareRequest"];
      };
    };
  };
  /** When applied, current subscription will be cancelled at the period end. */
  cancelSubscription: {
    parameters: {
      path: {
        organizationId: number;
      };
    };
    responses: {
      /** OK */
      200: unknown;
      /** Bad Request */
      400: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
    };
  };
  getPlan: {
    parameters: {
      path: {
        planId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["SelfHostedEePlanAdministrationModel"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
    };
  };
  updatePlan: {
    parameters: {
      path: {
        planId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["SelfHostedEePlanAdministrationModel"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SelfHostedEePlanRequest"];
      };
    };
  };
  deletePlan: {
    parameters: {
      path: {
        planId: number;
      };
    };
    responses: {
      /** OK */
      200: unknown;
      /** Bad Request */
      400: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
    };
  };
  getPlan_1: {
    parameters: {
      path: {
        planId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["CloudPlanAdministrationModel"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
    };
  };
  updatePlan_1: {
    parameters: {
      path: {
        planId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["CloudPlanAdministrationModel"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CloudPlanRequest"];
      };
    };
  };
  deletePlan_1: {
    parameters: {
      path: {
        planId: number;
      };
    };
    responses: {
      /** OK */
      200: unknown;
      /** Bad Request */
      400: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
    };
  };
  subscribe: {
    parameters: {
      path: {
        organizationId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["SubscribeModel"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CloudSubscribeRequest"];
      };
    };
  };
  getSelfHostedEeSubscriptions: {
    parameters: {
      path: {
        organizationId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["CollectionModelSelfHostedEeSubscriptionModel"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
    };
  };
  setupEeSubscription: {
    parameters: {
      path: {
        organizationId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["SubscribeModel"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SelfHostedEeSubscribeRequest"];
      };
    };
  };
  setupFreeEeSubscription: {
    parameters: {
      path: {
        organizationId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["SelfHostedEeSubscriptionModel"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SelfHostedEeFreeSubscribeRequest"];
      };
    };
  };
  getBuyMoreCreditsCheckoutSessionUrl: {
    parameters: {
      path: {
        organizationId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["BuyMoreCreditsModel"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BuyMoreCreditsRequest"];
      };
    };
  };
  getPlans_1: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["CollectionModelSelfHostedEePlanAdministrationModel"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
    };
  };
  create: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["SelfHostedEePlanAdministrationModel"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SelfHostedEePlanRequest"];
      };
    };
  };
  getPlans_2: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["CollectionModelCloudPlanAdministrationModel"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
    };
  };
  create_1: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["CloudPlanAdministrationModel"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CloudPlanRequest"];
      };
    };
  };
  getPlans: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["CollectionModelCloudPlanModel"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
    };
  };
  getMtCreditPrices: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["CollectionModelMtCreditsPriceModel"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
    };
  };
  getSubscription: {
    parameters: {
      path: {
        organizationId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["CloudSubscriptionModel"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
    };
  };
  getExpectedUsage: {
    parameters: {
      path: {
        organizationId: number;
        subscriptionId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["UsageModel"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
    };
  };
  getSelfHostedPlans: {
    parameters: {
      path: {
        organizationId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["CollectionModelSelfHostedEePlanModel"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
    };
  };
  /** Returns list of available cloud plans for specific organization.) */
  getCloudPlans: {
    parameters: {
      path: {
        organizationId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["CollectionModelCloudPlanModel"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
    };
  };
  getInvoices: {
    parameters: {
      path: {
        organizationId: number;
      };
      query: {
        /** Zero-based page index (0..N) */
        page?: number;
        /** The size of the page to be returned */
        size?: number;
        /** Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
        sort?: string[];
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["PagedModelInvoiceModel"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
    };
  };
  getUsage: {
    parameters: {
      path: {
        organizationId: number;
        invoiceId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["UsageModel"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
    };
  };
  /** Returns CSV file with usage detail for each time period and it's usage. */
  getUsageDetail: {
    parameters: {
      path: {
        organizationId: number;
        invoiceId: number;
        type: "SEATS" | "TRANSLATIONS";
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "text/csv": string;
        };
      };
      /** Bad Request */
      400: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
    };
  };
  getInvoicePdf: {
    parameters: {
      path: {
        organizationId: number;
        invoiceId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/pdf": string;
        };
      };
      /** Bad Request */
      400: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
    };
  };
  getExpectedUsage_1: {
    parameters: {
      path: {
        organizationId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["UsageModel"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
    };
  };
  goToCustomerPortal: {
    parameters: {
      path: {
        organizationId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["GoToCustomerPortalModel"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
    };
  };
  getBillingInfo: {
    parameters: {
      path: {
        organizationId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["BillingInfoModel"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
    };
  };
  getStripeProducts: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["CollectionModelStripeProductModel"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
    };
  };
  getPlanOrganizations: {
    parameters: {
      path: {
        planId: number;
      };
      query: {
        /** Zero-based page index (0..N) */
        page?: number;
        /** The size of the page to be returned */
        size?: number;
        /** Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
        sort?: string[];
        search?: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["PagedModelSimpleOrganizationModel"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
    };
  };
  getAllFeatures: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": (
            | "GRANULAR_PERMISSIONS"
            | "PRIORITIZED_FEATURE_REQUESTS"
            | "PREMIUM_SUPPORT"
            | "DEDICATED_SLACK_CHANNEL"
            | "ASSISTED_UPDATES"
            | "DEPLOYMENT_ASSISTANCE"
            | "BACKUP_CONFIGURATION"
            | "TEAM_TRAINING"
            | "ACCOUNT_MANAGER"
            | "STANDARD_SUPPORT"
            | "PROJECT_LEVEL_CONTENT_STORAGES"
            | "WEBHOOKS"
            | "MULTIPLE_CONTENT_DELIVERY_CONFIGS"
            | "AI_PROMPT_CUSTOMIZATION"
            | "SLACK_INTEGRATION"
            | "TASKS"
          )[];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
    };
  };
  getPlanOrganizations_1: {
    parameters: {
      path: {
        planId: number;
      };
      query: {
        /** Zero-based page index (0..N) */
        page?: number;
        /** The size of the page to be returned */
        size?: number;
        /** Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
        sort?: string[];
        search?: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["PagedModelSimpleOrganizationModel"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
    };
  };
  cancelEeSubscription: {
    parameters: {
      path: {
        organizationId: number;
        subscriptionId: number;
      };
    };
    responses: {
      /** OK */
      200: unknown;
      /** Bad Request */
      400: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Forbidden */
      403: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "application/json":
            | components["schemas"]["ErrorResponseTyped"]
            | components["schemas"]["ErrorResponseBody"];
        };
      };
    };
  };
}

export interface external {}
