/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v2/billing/create-customer-portal-session": {
    /** Returns url of Stripe checkout session */
    post: operations["createCustomerPortalSession"];
  };
  "/v2/billing/create-checkout-session": {
    /** Returns url of Stripe checkout session */
    post: operations["createCheckoutSession"];
  };
  "/v2/billing/subscriptions": {
    get: operations["getSubscriptions"];
  };
  "/v2/billing/subscription-state/{organizationId}": {
    get: operations["getSubscriptionState"];
  };
  "/v2/billing/plans": {
    get: operations["getPlans"];
  };
}

export interface components {
  schemas: {
    CreateCustomerPortalSessionRequest: {
      /** Id of the organization */
      organizationId?: number;
      /** Url to return afterwards */
      returnUrl: string;
    };
    CreateCheckoutSessionRequest: {
      /** Id of the organization */
      organizationId?: number;
      /** Url to return to when success */
      successUrl: string;
      /** Url to return to when cancelled */
      cancelUrl: string;
    };
    CollectionModelPlanModel: {
      _embedded?: {
        keys?: components["schemas"]["PlanModel"][];
      };
    };
    PlanModel: {
      name: string;
      translationLimit: number;
      includedMtCredits: number;
    };
  };
}

export interface operations {
  /** Returns url of Stripe checkout session */
  createCustomerPortalSession: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": string;
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": string;
        };
      };
      /** Not Found */
      404: {
        content: {
          "*/*": string;
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateCustomerPortalSessionRequest"];
      };
    };
  };
  /** Returns url of Stripe checkout session */
  createCheckoutSession: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": string;
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": string;
        };
      };
      /** Not Found */
      404: {
        content: {
          "*/*": string;
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateCheckoutSessionRequest"];
      };
    };
  };
  getSubscriptions: {
    responses: {
      /** OK */
      200: unknown;
      /** Bad Request */
      400: {
        content: {
          "*/*": string;
        };
      };
      /** Not Found */
      404: {
        content: {
          "*/*": string;
        };
      };
    };
  };
  getSubscriptionState: {
    parameters: {
      path: {
        organizationId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": { [key: string]: unknown };
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": string;
        };
      };
      /** Not Found */
      404: {
        content: {
          "*/*": string;
        };
      };
    };
  };
  getPlans: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["CollectionModelPlanModel"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": string;
        };
      };
      /** Not Found */
      404: {
        content: {
          "*/*": string;
        };
      };
    };
  };
}

export interface external {}
