package io.tolgee.ee.service.glossary.formats.csv

const val GLOSSARY_CSV_HEADER_TERM = "term"
const val GLOSSARY_CSV_HEADER_DESCRIPTION = "description"
const val GLOSSARY_CSV_HEADER_FLAG_TRANSLATABLE = "translatable"
const val GLOSSARY_CSV_HEADER_FLAG_CASE_SENSITIVE = "casesensitive"
const val GLOSSARY_CSV_HEADER_FLAG_ABBREVIATION = "abbreviation"
const val GLOSSARY_CSV_HEADER_FLAG_FORBIDDEN = "forbidden"

val GLOSSARY_CSV_HEADER_NAMES =
  listOf(
    GLOSSARY_CSV_HEADER_TERM,
    GLOSSARY_CSV_HEADER_DESCRIPTION,
    GLOSSARY_CSV_HEADER_FLAG_TRANSLATABLE,
    GLOSSARY_CSV_HEADER_FLAG_CASE_SENSITIVE,
    GLOSSARY_CSV_HEADER_FLAG_ABBREVIATION,
    GLOSSARY_CSV_HEADER_FLAG_FORBIDDEN,
  )
