name: Upload backend build
description: Compress and upload backend build result to GitHub artifacts

inputs:
  source-directory:
    description: Directory where the backend is. Defaults to current working directory.
    default: .

runs:
  using: composite
  steps:
    - name: Compress build results
      shell: bash
      env:
        SRC_DIR: ${{ inputs.source-directory }}
      run: |
        tar --zstd -cf ~/backend-api.tar.zst $SRC_DIR/backend/api/build
        tar --zstd -cf ~/backend-app.tar.zst $SRC_DIR/backend/app/build
        tar --zstd -cf ~/backend-data.tar.zst $SRC_DIR/backend/data/build
        tar --zstd -cf ~/backend-misc.tar.zst $SRC_DIR/backend/misc/build
        tar --zstd -cf ~/backend-security.tar.zst $SRC_DIR/backend/security/build
        tar --zstd -cf ~/backend-testing.tar.zst $SRC_DIR/backend/testing/build
        tar --zstd -cf ~/backend-ktlint.tar.zst $SRC_DIR/backend/ktlint/build
        tar --zstd -cf ~/backend-development.tar.zst $SRC_DIR/backend/development/build
        tar --zstd -cf ~/ee-backend-app.tar.zst $SRC_DIR/ee/backend/app/build
        tar --zstd -cf ~/ee-backend-tests.tar.zst $SRC_DIR/ee/backend/tests/build
        tar --zstd -cf ~/backend-email.tar.zst $SRC_DIR/email/out

    - name: Upload backend build result
      uses: actions/upload-artifact@v4
      with:
        name: backend
        path: |
          ~/backend-api.tar.zst
          ~/backend-app.tar.zst
          ~/backend-data.tar.zst
          ~/backend-misc.tar.zst
          ~/backend-security.tar.zst
          ~/backend-testing.tar.zst
          ~/backend-ktlint.tar.zst
          ~/backend-development.tar.zst
          ~/ee-backend-app.tar.zst
          ~/ee-backend-tests.tar.zst
          ~/backend-email.tar.zst
