name: Release

on:
  push:
    branches: ["tolgee-3"]

jobs:
  prerelease:
    uses: ./.github/workflows/release/publish.yml
    secrets: inherit
    with:
      docker-publish-method: manual
      deploy-testing: true
