name: Publish client prerelease

on:
  workflow_dispatch:
  push:
    branches: [main, release]
  pull_request:

jobs:
  publish-client-prerelease:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - run: echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > ~/.npmrc

      - name: Install node modules
        run: npm ci

      - name: Run get new version
        run: npm run release-dry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: Tolgee Machine
          GIT_COMMITTER_NAME: Tolgee Machine
          GIT_AUTHOR_EMAIL: machine@tolgee.io
          GIT_COMMITTER_EMAIL: machine@tolgee.io

      - name: Set version property
        id: version
        run: echo "VERSION=$(test -e .VERSION && echo v$(cat .VERSION))" >> $GITHUB_OUTPUT

      # client folder
      - name: install npm dependencies
        run: npm ci
        working-directory: ./client

      - name: update version and build
        run: |
          npm run update-version -- ${{ steps.version.outputs.VERSION }}-prerelease.$(git rev-parse --short HEAD)
          npm run build
        working-directory: ./client

      - name: publish
        run: npm publish --tag prerelease
        working-directory: ./client
