name: Publish client prerelease

on:
  workflow_dispatch:
  push:
    branches: [main, release]
  pull_request:

jobs:
  publish-client-prerelease:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          token: "${{ secrets.TOLGEE_MACHINE_PAT }}"

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - run: echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > ~/.npmrc

      # client folder
      - name: install npm dependencies
        run: npm ci
        working-directory: ./client

      - name: update version build and publish
        run: |
          VERSION=0.0.0-prerelease.$(git rev-parse --short HEAD)
          if npm view @tginternal/client@$VERSION versions --json >/dev/null 2>&1; then
            echo "Version $VERSION already exists, skipping publish."
          else
            npm run update-version -- $VERSION
            npm run build
            npm publish --tag prerelease
          fi
        working-directory: ./client
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
