name: Release

on:
  workflow_run:
    workflows: ["Test"]
    branches: ["main", "next"]
    types:
      - completed

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/release--publish.yml
    secrets: inherit
    with:
      use-machine-pat: true
      docker-publish-method: gradle
      trigger-billing: true
      tag-keys: true
