name: Optimized Test Execution

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  fast-tests:
    name: Fast Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      
      - name: Run Fast Tests
        run: ./gradlew fastTest
  
  repository-tests:
    name: Repository Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      
      - name: Run Repository Tests
        run: ./gradlew test --tests "io.tolgee.repository.*"
  
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [fast-tests, repository-tests]
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      
      - name: Run Integration Tests
        run: ./gradlew test --tests "io.tolgee.integration.*" 